#포트설정
server:
  port:  '8586'
#JSP설정
spring:
  mvc:
    view:
      prefix:  /WEB-INF/views
      suffix:  .jsp
#SMTP설정
  mail:
    host:  smtp.gmail.com
    port:  '587'
    username:  kt01022722867@gmail.com
    password:  bobo srev fpio qpih
    properties:
      mail:
        debug:  'true'
        smtp:
          connectiontimeout:  '5000'
          auth:  'false'
          starttls:
            enable:  'true'
            required:  'true' 